name: Build and Deploy Docs

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout main branch
      - uses: actions/checkout@v4

      # install Python 3.12, and cache pip dependencies
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r docs/requirements.txt

      # build the website, save output to _build folder
      # which is the folder name that actions/upload-pages-artifact@v2 expects by default
      - name: Build HTML docs
        run: make -C docs html

      #- name: Remove unneeded files
      #  run: rm -r _build/.doctrees _build/.buildinfo

      #- name: Upload artifact
      #        uses: actions/upload-pages-artifact@v2

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./docs/_build/html
          publish_branch: gh-pages
          allow_empty_commit: true
  # Deployment job
  #deploy:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #  runs-on: ubuntu-latest
  #   needs: build
  #  steps:
  #    - name: Deploy to GitHub Pages
  #      id: deployment
  #      uses: actions/deploy-pages@v2
